manifest:
  remotes:
  - name: zmkfirmware
    url-base: https://github.com/zmkfirmware
  - name: caksoylar
    url-base: https://github.com/caksoylar
  - name: kilipan
    url-base: https://github.com/kilipan
  projects:
  - name: zmk
    remote: zmkfirmware
    revision: main
    import: app/west.yml
  - name: zmk-keyboards-zilpzalp
    remote: kilipan
    revision: main
  - name: zmk-rgbled-widget
    remote: caksoylar
    revision: main
  self:
    path: config
